wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.1
    framework: xgboost
    huggingface_version: 4.45.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1729925232.84515
    t:
      1:
      - 1
      - 5
      - 6
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 77
      - 105
      3:
      - 13
      - 23
      4: 3.8.18
      5: 0.16.1
      6: 4.45.2
      8:
      - 5
      13: linux-x86_64
